### ISSUE TITLE
Null pointer exception using OnUi

### ISSUE THREAD

**Issue by cutiko** [KoMinkyu/teaspoon#6]
Im getting this error:

` E/AndroidRuntime: FATAL EXCEPTION: main
                                                 java.lang.NullPointerException
                                                     at teaspoon.processor.TeaSpoonProcessor.methodWithOnUiAnnotation(TeaSpoonProcessor.java:50)`

Im just doing the basic `OnUi` example, I try to do with delay time, same error. The problem is only happening in api V16, tested in a device V21 and it work.

**Comment by KoMinkyu** [comment]
Thank you for your report :)
This issue will be fixed on 0.3.4 version.
